### ISSUE TITLE
REQUEST: New membership for @ericzhang08

### ISSUE THREAD

**Issue by ericzhang08** [kubernetes/org#1098]
### GitHub Username
e.g. @ericzhang08

### Organization you are requesting membership in
e.g @kubernetes-sigs @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @chuckha 
- @ashish-amarnath

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/173
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/171
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/147
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/145
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/140
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/82
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/76
- Issues responded to
https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/150
https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/137
https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/66
https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/78
- SIG projects I am involved with: sig-cluster-lifecycle

**Comment by chuckha** [comment]
+1

thank you for all the contributions thus far and for always producing high quality code!

**Comment by ashish-amarnath** [comment]
+1 from me too!
Welcome! :tada:

**Comment by mrbobbytables** [comment]
Hey there @ericzhang08 , unfortunately @ashish-amarnath cannot sponsor you for membership in the @kubernetes org, but CAN sponsor you for membership in @kubernetes-sigs.

An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-csi etc); as long as it's a project they're involved with.

However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-csi cannot sponsor someone for membership in @kubernetes. They are scoped just to the org they're associated with.

@ericzhang08   If you'd like to amend your request to just @kubernetes-sigs, we can proceed with getting your membership processed. Otherwise, if you could, please find another sponsor from the @kubernetes org.

If you have any questions don't be afraid to ask.

Thanks!

**Comment by ericzhang08** [comment]
Hi @mrbobbytables, I have amended it.

**Comment by ericzhang08** [comment]
@xiangpengzhao

**Comment by xiangpengzhao** [comment]
Sure! +1 from me :)

**Comment by ericzhang08** [comment]
@mrbobbytables  I have found another one sponsor me.

**Comment by mrbobbytables** [comment]
Thanks for stepping in and adding your +1 for kubernetes org @xiangpengzhao :)

With that @ericzhang08 thank you for all your contributions so far :)

I've created PR #1105  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them

Welcome to @kubernetes & @kubernetes-sigs! 🎉

/assign
