### ISSUE TITLE
Migrating ip-masq-agent to @kubernetes-sigs

### ISSUE THREAD

**Issue by grayluck** [kubernetes/org#1154]
### New Repo, Staging Repo, or migrate existing
Migrate https://github.com/kubernetes-incubator/ip-masq-agent to kubernetes-sigs.

### Requested name for new repository
ip-masq-agent

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@bowei @dnardo @MrHohn @varunmar @grayluck

### If not a staging repo, who should have write access
@bowei @dnardo @MrHohn @varunmar @grayluck

### If not a staging repo, who should be listed as approvers in OWNERS
@bowei @dnardo @MrHohn @varunmar @grayluck

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@bowei @dnardo @MrHohn @varunmar @grayluck

### What should the repo description be
The ip-masq-agent configures iptables rules to MASQUERADE traffic outside link-local (optional, enabled by default) and additional arbitrary IP ranges.

### What SIG and subproject does this fall under in sigs.yaml
This belongs to subproject pod-networking under sig-network.

### Approvals
@thockin @dcbw @caseydavenport 

https://github.com/kubernetes/community/tree/master/sig-network

### Additional context for request
we're migrating from Kubernetes Incubator. That org is being archived.

**Comment by nikhita** [comment]
/assign @thockin @dcbw @caseydavenport 
for approval for the move

Btw this is also blocking the addition of new OWNERS: https://github.com/kubernetes-incubator/ip-masq-agent/pull/48

**Comment by thockin** [comment]
Approve.

**Comment by nikhita** [comment]
Repo has been migrated: https://github.com/kubernetes-sigs/ip-masq-agent :tada: 

I have also created:

- https://github.com/kubernetes/org/pull/1208 - to add GitHub teams for granting access. Also added @bowei @dnardo and @MrHohn to the kubernetes-sigs org since they are already members of the kubernetes org. @varunmar and @grayluck: can you create a [membership request](https://github.com/kubernetes/community/blob/master/community-membership.md#member) to be added to the kubernetes-sigs org? Once that's processed, please feel free to add yourself to the teams.yaml and OWNERS files. :)

- Updated the repo location in test-infra: https://github.com/kubernetes/test-infra/pull/14439

- Updated the repo location in sigs.yaml: https://github.com/kubernetes/community/pull/4104

Once all PRs merge, we can close the issue.

**Comment by nikhita** [comment]
Teams have been granted access.

**Comment by nikhita** [comment]
All PRs have merged :)

/close
