### ISSUE TITLE
Migrate external-dns to kubernetes-sigs

### ISSUE THREAD

**Issue by njuettner** [kubernetes/org#1286]
### New Repo, Staging Repo, or migrate existing
migrate existing (https://github.com/kubernetes-incubator/external-dns)

### Requested name for new repository
external-dns

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@Raffo @hjacobs @linki @njuettner

### If not a staging repo, who should have write access
@Raffo @hjacobs @linki @njuettner

### If not a staging repo, who should be listed as approvers in OWNERS
@Raffo @hjacobs @linki @njuettner

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@Raffo @hjacobs @linki @njuettner

### What should the repo description be
Configure external DNS servers (AWS Route53, Google CloudDNS and others) for Kubernetes Ingresses and Services.

### What SIG and subproject does this fall under in sigs.yaml
sig-network

### Approvals
TBD
https://groups.google.com/forum/#!topic/kubernetes-sig-network/KOpzXgWcCMA
https://github.com/kubernetes/enhancements/pull/1247

### Additional context for request
None

**Comment by nikhita** [comment]
Repo has been migrated https://github.com/kubernetes-sigs/external-dns :tada: 

I have created https://github.com/kubernetes/community/pull/4203 to update sigs.yaml in the k/community repo.

Also created #1353 to add GitHub teams to grant admin/write access to the repo.

According to our github membership rules, membership in the @kubernetes GitHub org implicitly grants you membership to @kubernetes-sigs. Since @linki is already a member of @kubernetes, I have added them to k-sigs in #1353.

@njuettner  @Raffo @hjacobs could you open issues for [membership requests](https://github.com/kubernetes/community/blob/master/community-membership.md#member)?

Once that's done, we can add you to the k-sigs org and you'll be able to lgtm/approve PRs in the external-dns repo. Until then, only @linki would be able to lgtm/approve.

**Comment by hjacobs** [comment]
@nikhita who should we add as sponsors for the membership request? (I only worked with External DNS and can't name core Kubernetes members I worked with closely)

**Comment by nikhita** [comment]
@hjacobs Feel free to add @linki (since they are a kubernetes member and external-dns approver), @mrbobbytables or me as sponsors. I've personally interacted with you at KubeCon as well, so I'm happy to vouch for you (sponsorship is mainly a sign of "the person has made significant contributions and I trust them"). :)

**Comment by nikhita** [comment]
All related PRs have merged.

/close
