### ISSUE TITLE
New repo kubernetes-sigs/ingress-controller-conformance

### ISSUE THREAD

**Issue by alexgervais** [kubernetes/org#1328]
### New Repo, Staging Repo, or migrate existing
migrate existing (https://github.com/datawire/ingress-conformance)

### Requested name for new repository
ingress-controller-conformance

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
bowei, thockin

### If not a staging repo, who should have write access
bowei, thockin, rhs, alexgervais

### If not a staging repo, who should be listed as approvers in OWNERS
bowei, thockin

### If not a staging repo, who should be listed in SECURITY_CONTACTS
bowei, thockin, rhs, alexgervais

### What should the repo description be
Repository for a compliance specification of ingress-controllers.

### What SIG and subproject does this fall under in sigs.yaml
sig-network

### Approvals
thockin
https://groups.google.com/forum/#!topic/kubernetes-sig-network/dAt78O-JUCo

### Additional context for request
The goal of this project is to act as an executable specification in the form of a test suite, implementing a standard, actively maintained ingress-controller conformance specification.

**Comment by mrbobbytables** [comment]
@alexgervais  just for clarification, are you looking for a bare repository? or to migrate [datawire/ingress-performance](https://github.com/datawire/ingress-conformance) to kubernetes-sigs?

If it's a migration or if the code is copied -- there are a few more steps involved to donate it to the Kubernetes project. For the specifics on that, please see the docs for it here:
https://git.k8s.io/community//github-management/kubernetes-repositories.md#rules-for-donated-repositories

**Comment by alexgervais** [comment]
@mrbobbytables We definitely want to contribute the code from datawire/ingress-performance. My thought was to create a bare repository and open a PR with the existing code, thus enforcing copywrite, licenses and other boilerplate.
All contributors to datawire/ingress-performance already signed the CNCF CLA.

I'm open to suggestions to make the copy/move as easy and transparent as possible.

**Comment by mrbobbytables** [comment]
I think that should be fine -- I don't see any dependencies that are outside the norm either. @nikhita what do you think?

**Comment by nikhita** [comment]
I'd suggest migrating/transfering the repo to the kubernetes-sigs org instead of going with a bare repo because it means different things with regards to copyright (IANAL though...). The `When I donate my project, am I transferring my copyrights?` part here has more details: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#faq.

Like @mrbobbytables mentioned, there are additional things required for migrating repos. Could you add the required files (LICENSE, code of conduct, etc) as mentioned here: https://git.k8s.io/community//github-management/kubernetes-repositories.md#rules-for-donated-repositories? Thanks!

**Comment by alexgervais** [comment]
The LICENSE and code-of-conduct.md files were added to the source repository.
The standard Kubernetes header to code can occur post-transfer.
@nikhita , @mrbobbytables please advise if you see any gaps!

**Comment by nikhita** [comment]
@alexgervais Two more things need to be done pre-transfer, but looks good otherwise. :+1: 

- Even though https://github.com/datawire/ingress-conformance/graphs/contributors shows a single contributor, the git log shows (merge) commits from @rhs and they haven't signed the CNCF CLA yet.
@rhs: if you could sign the CLA, we can move ahead with migrating the repo. Instructions can be found [here](https://github.com/kubernetes/community/blob/master/CLA.md).

- Once @rhs has signed the CLA, I can double-check and confirm. After that, please add me as an admin to the repo and I can transfer it to @kubernetes-sigs. :)

/assign

**Comment by rhs** [comment]
@nikhita @alexgervais Hi, I changed the one merge that was rhs@alum.mit.edu to rhs@datawire.io. I can see a corporate CLA in my account already, and I just signed an individual one. Please let me know if there is anything else you need from me. Thanks!

**Comment by nikhita** [comment]
@rhs Thanks for handling that so quick!

Everything looks good. :+1: Please add me as an admin to the repo so that I can transfer it. :)

**Comment by alexgervais** [comment]
Thank you @nikhita & @mrbobbytables

**Comment by nikhita** [comment]
I'll keep this open until https://github.com/kubernetes/community/pull/4208 is merged, so that it doesn't get lost. :)

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/4208 has merged
/close
