### ISSUE TITLE
please create repo cluster-bootstrap under kubernetes

### ISSUE THREAD

**Issue by yliaog** [kubernetes/org#137]
### New Repo, or migrate existing
new repository

### Requested name for new repository
cluster-bootstrap

### Which Organization should it reside
kubernetes

### Who should be provided access to this repository
sig-cluster-lifecycle-leads

### Approvals
Please detail out the approval process for the new repo
Requirements are listed here: https://git.k8s.io/community/github-management/kubernetes-repositories.md
If this is a core repository, then sig-architecture must approve
If this is a SIG repository, then the SIG Technical Leads must approve
Please include links to the approvals (meeting minutes, e-mail thread, etc)
approved by sig-architecture:

https://groups.google.com/forum/#!searchin/kubernetes-sig-architecture/cluster-bootstrap%7Csort:date/kubernetes-sig-architecture/d_E7JOyA4EM/IrlH5y1uBgAJ

### Additional context for request
Any additional information or context to describe the request.

**Comment by calebamiles** [comment]
done
https://github.com/kubernetes/cluster-bootstrap

/close

**Comment by nikhita** [comment]
Mentioning a list of PRs related to this because they are scattered around many repos. Refer https://github.com/kubernetes/kubernetes/blob/master/staging/README.md#creating-the-published-repository for the reason behind these PRs.

- https://github.com/kubernetes/cluster-bootstrap currently contains OWNERS, LICENSE and code-of-conduct.md. However, the directory should be empty so that the publishing bot does not encounter any conflicts while syncing from staging.

- https://github.com/kubernetes/publishing-bot/pull/89 added the cluster-bootstrap repo to the publishing bot. But later we realized that the directory should be empty, so we reverted it: https://github.com/kubernetes/publishing-bot/pull/118.

- Created https://github.com/kubernetes/cluster-bootstrap/pull/1 to remove these files from the published repo. One of the admins needs to merge it.

- This published repo also needs special permissions. Ref: https://github.com/kubernetes/org/issues/56#issue-356711512

- Created https://github.com/kubernetes/test-infra/pull/9702 to setup branch protection.

- Created https://github.com/kubernetes/community/pull/2748 to add it to sigs.yaml.

/cc @spiffxp @cblecker @sttts @yliaog

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/publishing-bot/pull/119 to add cluster-bootstrap to the publishing bot. Will remove the hold on it once permissions are updated.
