### ISSUE TITLE
Create repositories for blobfuse-csi-driver as a Cloud Provider Azure subproject 

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/org#1449]
### New Repo, or migrate existing
migrate repository

### Requested name for new repository
blobfuse-csi-driver

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@andyzhangx @khenidak @justaugustus @brendandburns  @feiskyer @lachie83

### If not a staging repo, who should have write access
@andyzhangx
@khenidak
@feiskyer
@brendandburns
@justaugustus
@lachie83

### If a new repo, who should be listed as approvers in OWNERS
@andyzhangx
@khenidak 
@feiskyer 
@brendandburns 
@justaugustus 
@lachie83

### If a new repo, who should be listed in SECURITY_CONTACTS
@andyzhangx
@khenidak 
@justaugustus 
@lachie83

### What should the repo description be
This driver allows Kubernetes to access azure blob storage.

### Approvals
1. SIG-AZURE Group reached consensus to create the repo  @justaugustus @feiskyer @khenidak  pls approve
2. Kubernetes code of conduct is adopted: https://github.com/csi-driver/blobfuse-csi-driver/blob/master/code-of-conduct.md
3. The repo uses Apache License v2: https://github.com/csi-driver/blobfuse-csi-driver/blob/master/LICENSE
4. CNCF CLA bot is enabled as a webhook on the repo.
5. All contributors have signed the CNCF individual or corporate CLA
6. The topic for the sponsoring SIG is added as k8s-sig-azure on the repository: https://github.com/csi-driver/blobfuse-csi-driver/blob/master/CONTRIBUTING.md
7. Fossabadge was added for a couple of 3rd party dependencies: https://app.fossa.io/projects/git%2Bgithub.com%2Fcsi-driver%2Fblobfuse-csi-driver?ref=badge_shield

TODO:

* Update [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) file after repo transfer is complete.

cc @kubernetes/steering-committee 
cc @ritazh @craiglpeters

**Comment by feiskyer** [comment]
Looks good to me

**Comment by mrbobbytables** [comment]
Assigning the cloud-provider leads for sign off.

/assign @andrewsykim @cheftako 
/sig cloud-provider

**Comment by andyzhangx** [comment]
@mrbobbytables do you know who will do the repo migration? I will add that github id into blobfuse driver org admin, thanks.

**Comment by nikhita** [comment]
@andyzhangx I can do that, since I'm around now. :)
Please add me as an admin to the repo. Thanks!

/assign

**Comment by andyzhangx** [comment]
> @andyzhangx I can do that, since I'm around now. :)
> Please add me as an admin to the repo. Thanks!
> 
> /assign

thanks, invited.

**Comment by nikhita** [comment]
Just adding this for the record:

- I have verified CLA, and all contributors have signed the CNCF CLA.
- I ran a FOSSA scan on the repo and while there were a few dependencies flagged, they were indirect dependencies due to vendoring in `k8s.io/kubernetes`. The flagged dependencies where indirectly being used by `k8s.io/kubernetes`, so I think this should be fine.
- Verified that the repo has all necessary template files.

**Comment by nikhita** [comment]
Repo has been migrated: https://github.com/kubernetes-sigs/blobfuse-csi-driver :tada: 

@andyzhangx I have not updated the OWNERS files since a bunch of approvers mentioned are not members of the @kubernetes-sigs org. They are being added in https://github.com/kubernetes/org/pull/1465, so once it merges, feel free to create a PR to add them to OWNERS files.

Also created:

- https://github.com/kubernetes/org/pull/1465 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4293 - to update sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by justaugustus** [comment]
@andyzhangx -- Can you provide a link to where this was discussed?

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/4293 has merged. Closing.

/close
