### ISSUE TITLE
Migrate custom-metrics-apiserver to kubernetes-sigs

### ISSUE THREAD

**Issue by s-urbaniak** [kubernetes/org#1597]
### New Repo, Staging Repo, or migrate existing
Migrate existing repository from https://github.com/kubernetes-incubator/custom-metrics-apiserver.

### Requested name for new repository
custom-metrics-apiserver

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@piosz 
@brancz 

### If not a staging repo, who should have write access
@s-urbaniak 
@serathius 

### If not a staging repo, who should be listed as approvers in OWNERS
@kawych 
@s-urbaniak 
@piosz 
@brancz 
@serathius 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@kawych 
@s-urbaniak 
@piosz 
@brancz 
@serathius 

### What should the repo description be
by default we will set it to "created due to (link to this issue)"

### What SIG and subproject does this fall under in sigs.yaml
this is part of Metrics API subproject for sig-instrumentation

### Approvals
/cc @brancz @s-urbaniak @kawych

**Comment by brancz** [comment]
This has my approval

**Comment by nikhita** [comment]
Repo has been migrated: https://github.com/kubernetes-sigs/custom-metrics-apiserver :+1: 

Created:

- https://github.com/kubernetes/org/pull/1598 - to update GitHub teams
- https://github.com/kubernetes/community/pull/4457 - to update sigs.yaml

We can close this issue once both PRs merge.

@s-urbaniak I haven't updated OWNERS or SECURITY_CONTACTS since they can be updated through the normal PR process now. Also, not sure if anything related to the travis webhook needs update, but I haven't removed the webhook yet. You should be able to update the webhooks once https://github.com/kubernetes/org/pull/1598 merges and the GitHub team gets admin access. :)

**Comment by nikhita** [comment]
All PRs have merged and teams have been granted access.

/close

**Comment by s-urbaniak** [comment]
thank you @nikhita! :raised_hands:
