### ISSUE TITLE
REQUEST: New membership for @IanColdwater

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/org#1636]
### GitHub Username
I'm recommending to add @IanColdwater as a member to the github/kubernetes organization.
They're a valuable commuity member, and I'm more than happy to sponsor their membership. I'll leave it to Ian to fill out the requirements details below.

edit: please copy/paste in a followup comment, since editing is disabled

### Organization you are requesting membership in
Kubernetes, kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @guineveresaenger 
- @ehashman 

### List of contributions to the Kubernetes project (add in comment below)
I've put in one issue (kubernetes/website#18129), but most of my contributions so far have been outside of GitHub. I've been spreading awareness about Kubernetes and Kubernetes security for years, by doing talks from big conferences to small meetups and helping people online on Twitter and Slack. I've been in SIG-auth for a minute (although I can't make it to meetings due to a conflict) and have helped folks in other SIGs (security, docs, sig-docs-security, cli, rainbow) with ideas in various places. I'm also helping to organize a contributor offsite and have done a fair amount of hard to quantify glue work. And I've keynoted KubeCon, for what that's worth. :)

**Comment by markyjackson-taulia** [comment]
Huge +1 from me

**Comment by justaugustus** [comment]
An enthusiastic +1 for this!!
Also, honks. Lots of honks.

/honk

**Comment by ehashman** [comment]
Confirming my sponsorship!

/honk

**Comment by cblecker** [comment]
/hold
Holding until this is fully processed with all needed information.

**Comment by IanColdwater** [comment]
### Organization you are requesting membership in
Kubernetes, kubernetes-sigs

### Requirements
* [x]  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
* [x]  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
* [x]  I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
* [x]  I am actively contributing to 1 or more Kubernetes subprojects
* [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
* [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
* @guineveresaenger
* @ehashman

### List of contributions to the Kubernetes project (add in comment below)

I've put in one issue (https://github.com/kubernetes/website/issues/18129), but most of my contributions so far have been outside of GitHub. I've been spreading awareness about Kubernetes and Kubernetes security for years, by doing talks from big conferences to small meetups and helping people online on Twitter and Slack. I've been in SIG-auth for a minute (although I can't make it to meetings due to a conflict) and have helped folks in other SIGs (security, docs, sig-docs-security, cli, rainbow) with ideas in various places. I'm also helping to organize a contributor offsite and have done a fair amount of hard to quantify glue work. And I've keynoted KubeCon, for what that's worth. :)

**Comment by guineveresaenger** [comment]
updated with your text (for I think bot reasons?) yay!

**Comment by mauilion** [comment]
+1 and /honk

**Comment by justaugustus** [comment]
@IanColdwater -- Thanks so much for your contributions thus far!
I've created https://github.com/kubernetes/org/pull/1639 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
/pony party

**Comment by justaugustus** [comment]
> updated with your text (for I think bot reasons?) yay!

@guineveresaenger -- Not bot stuff; just my own sanity :sweat_smile:
