### ISSUE TITLE
Create kubernetes-sigs/kubebuilder-release-tools

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/org#1710]
### New Repo, Staging Repo, or migrate existing

New repo

### Requested name for new repository

kubernetes-sigs/kubebuilder-release-tools

### Which Organization should it reside

kubernetes-sigs

### If not a staging repo, who should have admin access

The active parts of the kubebuilder admins & maintainers:

- @DirectXMan12 
- @droot 
- @mengqiy 
- @vincepri 

### If not a staging repo, who should have write access

Above ^

### If not a staging repo, who should be listed as approvers in OWNERS

Please copy kubernetes-sigs/kubebuilder's OWNERS and OWNERS_ALIASES structure (we can clean up from there)

### If not a staging repo, who should be listed in SECURITY_CONTACTS

ditto ^

### What should the repo description be

"Release tooling for KubeBuilder projects"

### What SIG and subproject does this fall under in sigs.yaml

SIG API Machinery / KubeBuilder (a.k.a. server-sdk)

### Approvals

- [x] @DirectXMan12 (subproject lead)
- [x] @pwittrock (subproject repository creation approver)

### Additional context for request

We'd like a central place to store our release and extra validation tooling (release notes generation scripts, PR verifier scripts, etc) to easily consume across CR, CT, and KB, plus other repos with interest (I believe @vincepri mentioned that cluster API has a copy of our scripts).

/area github-repo

**Comment by mrbobbytables** [comment]
/assign @pwittrock 
for sign off 👍

**Comment by nikhita** [comment]
Repo has been created: https://github.com/kubernetes-sigs/kubebuilder-release-tools :+1: 

Also created:
- https://github.com/kubernetes/org/pull/1761 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4659 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by justaugustus** [comment]
@DirectXMan12 @pwittrock @vincepri -- one note: there's a release notes generator tool in k/release: https://github.com/kubernetes/release/tree/master/cmd/release-notes which can be used for non-k/k repos as well.

There's a little manually massaging to do, but I do use it for capz.

Here's an [example](https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/tag/v0.4.0): 

## Cluster API Azure (`v1alpha3`)

### Cluster API support
This release supports the `v1alpha3`/`v0.3.x` version of [Cluster API](https://github.com/kubernetes-sigs/cluster-api)

### Getting started
Quick start: https://cluster-api.sigs.k8s.io/user/quick-start.html

### Upgrading from v1alpha2
To upgrade from a running management cluster based on v1alpha2, follow [these instructions](https://cluster-api.sigs.k8s.io/tasks/upgrade.html#upgrading-from-cluster-api-v1alpha2-to-cluster-api-v1alpha3) in the book.

### Changes since v0.3.0

- e2e/tests: Use CAPI e2e framework ([#421](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/421), [@cpanato](https://github.com/cpanato))
- bump controller-tools to version v.0.2.5 ([#382](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/382), [@cpanato](https://github.com/cpanato))
- liveness and readiness probes added ([#374](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/374), [@cpanato](https://github.com/cpanato))
- Add clusterctl-settings.json ([#401](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/401), [@CecileRobertMichon](https://github.com/CecileRobertMichon))
- Add links for the developer getting started ([#383](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/383), [@jsturtevant](https://github.com/jsturtevant))
- Add proposal issue template based on CAPI template ([#396](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/396), [@devigned](https://github.com/devigned))
- Added v1alpha2 to v1alpha3 conversion webhooks ([#380](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/380), [@CecileRobertMichon](https://github.com/CecileRobertMichon))
- Bump Azure SDK to v40.4.0 ([#459](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/459), [@cpanato](https://github.com/cpanato))
- Capi: update cluster-api to v0.3.0 ([#438](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/438), [@cpanato](https://github.com/cpanato))
- Change example OS disk size to 128GB ([#445](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/445), [@CecileRobertMichon](https://github.com/CecileRobertMichon))
- Change the APIServer health probe to HTTPS ([#444](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/444), [@CecileRobertMichon](https://github.com/CecileRobertMichon))
- Deps: bump github.com/golang/mock to 1.4.0 ([#398](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/398), [@cpanato](https://github.com/cpanato))
- Fix capi selector in make create-cluster ([#399](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/399), [@CecileRobertMichon](https://github.com/CecileRobertMichon))
- Images specified using new resource kinds (`AzureMarketplaceImage`, `AzureSharedGalleryImage`, `AzureImageByID`). ([#334](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/334), [@richardcase](https://github.com/richardcase))
- Make NAT Rules creation and deletion owned by network interfaces ([#451](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/451), [@CecileRobertMichon](https://github.com/CecileRobertMichon))
- Refactor kustomize config folder ([#393](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/393), [@nader-ziada](https://github.com/nader-ziada))
- Remove examples and switch add cluster-template ([#424](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/424), [@CecileRobertMichon](https://github.com/CecileRobertMichon))
- Update README and getting started docs ([#373](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/373), [@CecileRobertMichon](https://github.com/CecileRobertMichon))
- Update to CRD v1 ([#391](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/391), [@CecileRobertMichon](https://github.com/CecileRobertMichon))
- Updated default k8s version to 1.16.7 ([#414](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/414), [@CecileRobertMichon](https://github.com/CecileRobertMichon))

The image for this release is `us.gcr.io/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller:v0.4.0`.

_Thanks to all our contributors!_ :blush:

**Comment by justaugustus** [comment]
Would be cool if we could consolidate (where it makes sense) to k/release.

**Comment by nikhita** [comment]
Going to close this since all PRs have merged and teams have been granted access.

/close

**Comment by DirectXMan12** [comment]
@justaugustus it's mainly that our stuff is fairly different than k/release ATM.  I'm not sure how much sense it makes to unify (we specifically avoided needing github access and use emojis, etc).  That's mainly why I haven't investigated unifying further.
