### ISSUE TITLE
New repo for kubernetes-incubator/external-storage/tree/master/nfs-client

### ISSUE THREAD

**Issue by kmova** [kubernetes/org#1744]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
nfs-subdir-external-provisioner

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@jsafrane
@msau42 
@saad-ali
@xing-yang 

### If not a staging repo, who should be listed as approvers in OWNERS
@wongma7
@jsafrane
@kmova
@ashishranjan738
@zimmertr

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@jsafrane
@msau42
@saad-ali
@xing-yang 

### What should the repo description be
Dynamic sub-dir volume provisioner on a remote NFS server. 

### What SIG and subproject does this fall under in sigs.yaml
sig-storage

### Approvals
Need sig-storage approval from: @jsafrane, @saad-ali and @xing-yang 

See "Create K8s sig projects for NFS provisioners" in https://docs.google.com/document/d/11QrSFVpI7lVpT5giwZpBQydRgCPLNs-XBgKY8kdt4gU/edit?ts=5e7aacc3#heading=h.9usnv9hqc1f6

### Additional context for request
[kubernetes-incubator/external-storage](https://github.com/kubernetes-incubator/external-storage) was marked as deprecated and there is an [active proposal](https://github.com/kubernetes/org/issues/1563) to deprecate the https://github.com/kubernetes-incubator/ org. Most of the actively maintained projects in the external-storage repository have been moved out either into kubernetes-sigs org or to specific CSI driver projects. 

Creating a kubernetes sig project for the [NFS Subdir Provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client) will provide the users, contributors and maintainers a best neutral home governed by the Kubernetes community guidelines and governance.

/area github-repo
/sig storage

**Comment by xing-yang** [comment]
Can you also add @msau42 to admin access and security_contacts list?

Other than that, it looks good to me.

**Comment by nikhita** [comment]
@kmova @xing-yang Has the repo name been finalized? I see some open comments here about the repo name - https://docs.google.com/document/d/11QrSFVpI7lVpT5giwZpBQydRgCPLNs-XBgKY8kdt4gU/edit?ts=5e7aacc3#

**Comment by xing-yang** [comment]
I see that @msau42 has suggested to add "external" to the name.  @msau42 are you okay with the proposed repo name in this PR?

**Comment by mrbobbytables** [comment]
I do have a couple other questions -- for this and the other nfs repo is the eventual goal to migrate to the csi based provisioning method? If so, should it be moved to kubernetes-csi? or would these eventually be deprecated fully in favor of a csi based provisioning method?

**Comment by kmova** [comment]
@msau42 - went ahead and proposed to include the `external` in the name. It also helps with the confusion of whether this will be under CSI or sigs. ( cc: @mrbobbytables )

**Comment by saad-ali** [comment]
> I do have a couple other questions -- for this and the other nfs repo is the eventual goal to migrate to the csi based provisioning method? If so, should it be moved to kubernetes-csi? or would these eventually be deprecated fully in favor of a csi based provisioning method?

My 2 cents: If/when we migrate these to CSI, we can deprecate these repos and create new ones under kubernetes-csi.

Do we need sig-storage in the name? No strong opinion either way from me.

Otherwise
/lgtm
from me

Let's make sure to get LGTM from @xing-yang @msau42 @jsafrane and approval from @mrbobbytables and @nikhita before merging.

**Comment by xing-yang** [comment]
I don't have a strong opinion on whether sig-storage should be in the repo name or not.

/lgtm

**Comment by nikhita** [comment]
> Do we need sig-storage in the name?

In the past, we haven't included the SIG's name in the repo name and given that it doesn't provide any additional information, I'd say that we don't have it. Lgtm otherwsie. :+1:

**Comment by kmova** [comment]
As it happens, there are only two repos with a sig prefix under the kubernetes-sigs:
- https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
- https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner

This was probably a convention earlier, but not anymore. 

After sounding it off with @msau42  - I removed the sig-storage prefix from the names.

**Comment by nikhita** [comment]
Repo has been created: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner :+1: 

I have also created:

- https://github.com/kubernetes/org/pull/1750 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4654 - to add repos to sigs.yaml

Once both PRs merge, we can close this issue.

---

@kmova @ashishranjan738 @zimmertr I was not able to add you as approver for the repo because approvers need to be members of the @kubernetes-sigs org. You will need to submit an issue to this repo to be added to the org, more details [here](https://github.com/kubernetes/community/blob/master/community-membership.md#member). Once you are added to the org, feel free to create a PR to add yourself in as an approver.

---

Also, could you also do the migration of the code from the incubator repo to the new one and then ping at https://github.com/kubernetes/org/issues/1563 after that's done so that we can archive the incubator repo?

**Comment by justaugustus** [comment]
One thing you'll want to look into is now that the second name change (into k-sigs) might break downstream consumers.

AFAIK, GH will redirect through one repo name change. I'm not sure about two.

**Comment by nikhita** [comment]
> One thing you'll want to look into is now that the second name change (into k-sigs) might break downstream consumers.

I probably need more coffee :) but can you elaborate on when we would need the second name change in k-sigs?

**Comment by justaugustus** [comment]
Wait, nvm. I thought it was the original repo had the `sig-storage` prefix in the name and that had already been renamed.

I'm seeing now that's it's a folder within an existing repo 😅

**Comment by nikhita** [comment]
Closing since teams have been setup and sigs.yaml updated.
