### ISSUE TITLE
REQUEST: New membership for Adirio

### ISSUE THREAD

**Issue by Adirio** [kubernetes/org#1820]
### GitHub Username
@Adirio

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @DirectxMan12
- @alexeldeib

### List of contributions to the Kubernetes project
- PRs authored in [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder) (54 at application time): [link](https://github.com/kubernetes-sigs/kubebuilder/pulls?utf8=%E2%9C%93&q=author%3AAdirio)
- PRs reviewed in [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder) (60 at application time): [link](https://github.com/kubernetes-sigs/kubebuilder/issues?utf8=%E2%9C%93&q=reviewed-by%3AAdirio+-author%3AAdirio)
- Issues responded to in [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder) (50 at application time): [link](https://github.com/kubernetes-sigs/kubebuilder/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3AAdirio+-author%3AAdirio)
- SIG projects I am involved with: [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder) ([contributors](https://github.com/kubernetes-sigs/kubebuilder/graphs/contributors)) and related tools, belonging to `sigs-api-machinery`

**Comment by alexeldeib** [comment]
+1, @Adirio has been helping out a bunch with Kubebuilder. Time to make it official in the org 🙂

**Comment by DirectXMan12** [comment]
:+1: from me as well

**Comment by mrbobbytables** [comment]
@Adirio did you mean the kubernetes or the kubernetes-sigs org?

@alexeldeib unfortunately  cannot sponsor you for membership in the @kubernetes org, but CAN sponsor you for membership in @kubernetes-sigs.

An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-csi etc); as long as it's a project they're involved with.

However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-csi cannot sponsor someone for membership in @kubernetes. They are scoped just to the org they're associated with.

@Adirio  If you'd like to amend your request to just @kubernetes-sigs, we can proceed with getting your membership processed. Otherwise, if you could, please find another sponsor from the @kubernetes org.

If you have any questions don't be afraid to ask.

Thanks!

**Comment by alexeldeib** [comment]
@mrbobbytables the purpose of this PR is described in https://github.com/kubernetes/test-infra/pull/17241#issuecomment-615330612

It's not actually at all related to kubernetes-sigs, it's related to test-infra, which @Adirio and I both help work on.

If that's not acceptable, is there a recommended way in the Kubernetes org to have test-infra access for Kubernetes-sigs members who maintain test-infra support? Seems a bit backwards you're able to approve/review a project, contribute to its test infrastructure, but not approve/review that test infrastructure because you can't become a k/k member.

WDYT?

**Comment by alexeldeib** [comment]
(n.b. I realized I'm not currently a review in k/k either, but that test-infra adds me as one -- I thought it already merged)

**Comment by Adirio** [comment]
@mrbobbytables I'm already part of @kubernetes-sigs, I was asking for @kubernetes membership for the reason mentioned by @alexeldeib, thought he was a member.

**Comment by alexeldeib** [comment]
Just to clarify, merging https://github.com/kubernetes/test-infra/pull/17241 is actually sufficient for me to approve this, right?

I pinged @Adirio offline to apologize for the confusion and let him know he's free to find another sponsor, but I'd rather just wait for the test-infra PR to merge to make this kosher.

I'm still curious about the edge case of test-infra given its nature and wide use across Kubernetes SIGs -- is this something that has been discussed?

**Comment by mrbobbytables** [comment]
@alexeldeib It would be -- with that in flight and sign off from @DirectXMan12 , I'm okay with moving forward on this one 👍 

@Adirio I'll append your org membership to PR #1836 here in a minute. 😄

**Comment by mrbobbytables** [comment]
Sorry for the back and forth a bit. This has come up a few times, but in general is pretty rare.

On a  lighter note...
@Adirio  -- I've added you to the Kubernetes Org in #1836 . Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
