### ISSUE TITLE
REQUEST: New membership for @Dhiraj240

### ISSUE THREAD

**Issue by Dhiraj240** [kubernetes/org#1883]
### GitHub Username
@Dhiraj240
### Organization you are requesting membership in
@Kubernetes-SIGs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@andyzhangx 
@JimBugwadia 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/279
https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/265
- Issues responded to
https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/258
https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/278
https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/266

- SIG projects I am involved with
https://github.com/kubernetes-sigs/azurefile-csi-driver
https://github.com/kubernetes-sigs/wg-policy-prototypes

**Comment by mrbobbytables** [comment]
@Dhiraj240 , unfortunately @JimBugwadia cannot sponsor you for membership in the @kubernetes org, but CAN sponsor you for membership in @kubernetes-sigs.

An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-csi etc); as long as it's a project they're involved with.

However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-csi cannot sponsor someone for membership in @kubernetes. They are scoped just to the org they're associated with.

@Dhiraj240  If you'd like to amend your request to just @kubernetes-sigs, we can proceed with getting your membership processed. Otherwise, if you could, please find another sponsor from the @kubernetes org.

If you have any questions don't be afraid to ask.

Thanks!

**Comment by Dhiraj240** [comment]
@mrbobbytables Process with @kubernetes-sigs and also process with those in which @andyzhangx  is he is part of @kubernetes  and @kubernetes-csi  as I am mostly involved in his projects

**Comment by nikhita** [comment]
@andyzhangx @JimBugwadia can you +1 here if this looks good to you?

**Comment by nikhita** [comment]
As there has been no traction with this for a while I'm going to flag it as rotten.

/lifecycle rotten

Please remember that you must speak to your sponsors first and get their approval before applying for org membership.

If this is still active, please go ahead and /remove-lifecycle rotten

**Comment by Dhiraj240** [comment]
@nikhita  Understood, they are not responsive now but I will look for other project contributions and their mentors.
Closing it now, no more expectations.
