### ISSUE TITLE
Need help on migration of kubernetes-incubator/external-storage/tree/master/nfs

### ISSUE THREAD

**Issue by kmova** [kubernetes/org#1921]
We are in the process of migrating `kubernetes-incubator/external-storage/tree/master/nfs` to `https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner`. 

As [directed](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/2#issuecomment-640854088) by @dims, raising this issue for help with resolving the CLA error on the migration PR: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/2

The CLA error is caused by older commits associated with deleted/uknown github handle.

**Comment by kmova** [comment]
Tagging @nikhita @idvoretskyi for help.

**Comment by nikhita** [comment]
While migrating code between Kubernetes repos in the past, we have merged manually -- this is equal to clicking on the "Merge" button on GitHub. We have done that before because we assumed that the commits had the CNCF CLA signed at the time it was merged. See [sig-arch thread](https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/lohdOInzcuQ), particularly:

> My understanding is that this is a totally justified override of the CLAbot since you're not introducing any new code to the project, just reshuffling existing code.

---

In this case, the PR https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/2 gets the `cncf-cla:no` label for 2 reasons:

- Missing GitHub users for commits like https://github.com/kubernetes-incubator/external-storage/commit/2cb2668f83f2349b661b14a0cff9e2304ec39e87. These commits had the cla signed at the time of merge (https://github.com/kubernetes-incubator/external-storage/pull/645).

- Commits where the CLA was not signed at the time of merge. There is only such commit - https://github.com/kubernetes-incubator/external-storage/commit/712682ba5bb335fab9f5da46ba803e20d1837802, see related PR https://github.com/kubernetes-incubator/external-storage/pull/633.

I think we can merge manually once the author for https://github.com/kubernetes-incubator/external-storage/commit/712682ba5bb335fab9f5da46ba803e20d1837802 has signed the CLA.

---

@initcron can you sign the [CNCF CLA](https://github.com/kubernetes/community/blob/master/CLA.md) so that we can proceed with migrating code? Please don't hesitate to reach out if you face any trouble while doing so! :)

@swinslow @caniszczyk Please take a look. Is having @initcron sign the CLA enough (or do we not need this)? Are there any other things we'd need to do from a legal perspective?

**Comment by nikhita** [comment]
@initcron :wave: friendly ping about singing the [CLA](https://github.com/kubernetes/community/blob/master/CLA.md)

**Comment by nikhita** [comment]
Looks like we aren't able to reach @initcron. For reference, I tried to reach them on twitter a week ago as well - https://twitter.com/TheNikhita/status/1272390172315807751

@kmova in cases like these, we usually just remove the problematic commit and add the changes ourselves in a new commit. Specifically in this case, it would involve removing https://github.com/kubernetes-incubator/external-storage/commit/712682ba5bb335fab9f5da46ba803e20d1837802 from the PR and adding the changes introduce by that commit separately in a new commit.

After that's done, it should be fine to merge the PR manually. If you'd like, I'm happy to review the PR before the manual merge after the above change has been made.

**Comment by kmova** [comment]
The changes made by the commit in question were updated in later commits and the files moved to a new location. I created a new PR by dropping that commit. 

The changes from the above commit are reflected here:
https://github.com/kmova/nfs-ganesha-server-and-external-provisioner/blob/cherry-pick-code/deploy/kubernetes/rbac.yaml#L1
https://github.com/kmova/nfs-ganesha-server-and-external-provisioner/blob/cherry-pick-code/deploy/kubernetes/rbac.yaml#L26

Here is the new PR: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/3

The new PR needs help in removing the `do-not-merge/invalid-commit-message` label. ( cc: @msau42 )

**Comment by nikhita** [comment]
@kmova The new PR looks good! I have removed the label for you and commented on the PR with confirmation about the CLA issue - https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/3#issuecomment-648973160. Please feel free to merge manually when you are ready. :+1: 

With that, I'll go ahead and close this issue. Please reopen if you need further help! :)
