### ISSUE TITLE
area/github-management does not exist in this repo

### ISSUE THREAD

**Issue by fejta** [kubernetes/org#1993]
area/github-membership does:

https://github.com/kubernetes/test-infra/blob/8795b499fa947e1cbcb15e947ed2b50aa65e4837/label_sync/labels.yaml#L1004-L1020

but area/github-management only exists in test-infra and community

We should either create this label or stop trying to make PRs create it:

https://github.com/kubernetes/org/blob/654cbb8d184c805602efd21e45d473884f709b26/OWNERS#L20-L21

**Comment by nikhita** [comment]
Let's add it.

I'm going to label this as a good first issue so that someone new can understand how the label sync process works :)

/good-first-issue

**Comment by nikhita** [comment]
For anyone picking this up, here's how to go about it:

Since we have lots of repos and lots of GitHub orgs in the upstream Kubernetes project, we need a way to make sure that all repos have the same minimum set of labels and that we have a way to document and define labels in a transparent way.

We manage this through (yet another) yaml file today :)

The labels are defined in https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml. https://github.com/kubernetes/test-infra/tree/master/label_sync contains general info about how the yaml file is structure and how to use it.

For this issue:

1. You'd need to add `area/github-management` under the `kubernetes/org` key similar to other labels here - https://github.com/kubernetes/test-infra/blob/8795b499fa947e1cbcb15e947ed2b50aa65e4837/label_sync/labels.yaml#L1004-L1020.

2. Once that's done, a few files need to be autogenerated. Running the last command listed in https://github.com/kubernetes/test-infra/tree/master/label_sync#usage will generate them.

**Comment by meghanagupta** [comment]
Hi! I'm interested in taking this up.

**Comment by fejta** [comment]
Leave an `/assign` comment then and prow will assign it to you :)

**Comment by meghanagupta** [comment]
My bad, think I got a bit late to mark it. Thanks anyway :)
