### ISSUE TITLE
REQUEST: New membership for cwdsuzhou

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/org#2156]
### GitHub Username

cwdsuzhou

### Organization you are requesting membership in

kubernetes-sigs

I'm a kubernetes org member and I am working on scheduler-plugins (coscheduling with PodGroup CRD， https://github.com/kubernetes-sigs/scheduler-plugins/pull/42), I would like to be a member to help me submit code more conveniently.

Thanks!

**Comment by Huang-Wei** [comment]
+1!

@cwdsuzhou has contributed over 50+ PRs to k/k, and now is actively working in both default scheduler and the scheduler-plugins subrepo.

BTW: @cwdsuzhou it'd be good to follow the membership template (e.g., #2147) to list all PRs/reviews you have done:

- 56 merged PRs: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Amerged+author%3Acwdsuzhou
- 83 reviewed PRs: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+reviewed-by%3Acwdsuzhou
- 68 issues commented: https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Acwdsuzhou

**Comment by palnabarun** [comment]
@cwdsuzhou -- Thank you for all that you have been doing for the scheduling projects. :tada: 

I see that you are already a member of @kubernetes. Since you are requesting for membership to @kubernetes-sigs, you can just PR yourself into https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/org.yaml by mentioning your contributions in the PR body. 

For more details, please have a look at https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem. Here is an example: https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/org.yaml

Do let me know if you have any doubts. :slightly_smiling_face: 

Thank you!

**Comment by cwdsuzhou** [comment]
Thanks @palnabarun

**Comment by cwdsuzhou** [comment]
https://github.com/kubernetes/org/pull/2171

@palnabarun PR sent, PTAL thanks
