### ISSUE TITLE
REQUEST: New membership for @hardikdr

### ISSUE THREAD

**Issue by hardikdr** [kubernetes/org#216]
### GitHub Username
@hardikdr

### Organization you are requesting membership in
@kubernetes-sigs
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @roberthbailey 
- @chaosaffe 
- @nikhita 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes/kubernetes/pull/54385
  * https://github.com/kubernetes/website/pull/9321
  * https://github.com/kubernetes-sigs/cluster-api/pull/483
  * https://github.com/kubernetes-sigs/cluster-api/pull/488
  * https://github.com/kubernetes-sigs/cluster-api/pull/511
  * https://github.com/kubernetes-sigs/cluster-api/pull/531

- Issues responded to
  * https://github.com/kubernetes/kubernetes/issues/12455
  * https://github.com/kubernetes-sigs/cluster-api/issues/490
  * https://github.com/kubernetes-sigs/cluster-api/issues/47
  * https://github.com/kubernetes/website/pull/9321

- SIG projects I am involved with https://github.com/kubernetes-sigs/cluster-api

/area github-membership

**Comment by chaosaffe** [comment]
+1 from me!

@hardikdr Thank you for all your work so far, and happy to have you as part of the org 😍

**Comment by mrbobbytables** [comment]
Hey there @hardikdr. Unfortunately, @chaosaffe cannot sponsor you for membership in the @kubernetes org, but CAN sponsor you for the @kubernetes-sigs org. 

An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-incubator etc); as long as its a project they're involved with. 

However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-sigs cannot sponsor someone for membership in @kubernetes. They are scoped just to the org they're associated with.

If you'd like to amend your request to just @kubernetes-sigs, we can proceed with getting your membership processed. Otherwise, if you could, please find another sponsor from the @kubernetes org. 

If you have any questions don't be afraid to ask.

Thanks!

**Comment by nikhita** [comment]
+1

I am happy to act as a sponsor for @hardikdr. He has made numerous contributions to the Cluster API subproject and is an active participant in meetings. He has also written a [proposal](https://docs.google.com/document/d/12TsBPn1lfMk50_yydzbXNZ9PT-8-88o4tSNi7eqPCVg/edit#heading=h.fafx2l7zb1b4) for a feature.

Also, just for complete clarity, I am listed in the following OWNERS files: https://cs.k8s.io/?q=nikhita&i=fosho&files=OWNERS&repos=

**Comment by hardikdr** [comment]
Thanks a lot @nikhita, for being a sponsor 🙂

@mrbobbytables Thank you for clarification. I updated the Issue to include @nikhita  as a sponsor. Please let me know if there is anything required yet. 🙂

**Comment by cblecker** [comment]
Invite will be sent out as soon as #220 merges. Welcome to @kubernetes! 🚀
