### ISSUE TITLE
Please remove mbohlool from java-admins

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/org#2169]
### Organization or repository
kubernetes-client/java

### Users affected
mbohlool

### Describe the issue
mbohlool has been inactive on the repository for a long time but continues to be assigned to issues and PRs by the github automation, removing him from the java-admins group will help eliminate this.

**Comment by brendandburns** [comment]
cc @mbohlool

**Comment by nikhita** [comment]
> mbohlool has been inactive on the repository for a long time but continues to be assigned to issues and PRs by the github automation, removing him from the java-admins group will help eliminate this.

To avoid mbohlool to be automatically requested for reviews on PRs, he needs to be removed from the OWNERS file. I see that https://github.com/kubernetes-client/java/pull/1220 did that.

Since he's inactive, I've also created https://github.com/kubernetes/org/pull/2174 to remove him from the admins list.
