### ISSUE TITLE
REQUEST: New membership for howardjohn

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/org#2183]
### GitHub Username
@howardjohn

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @robscott 
- @hbagdi

### List of contributions to the Kubernetes project
- PRs reviewed / authored: https://github.com/kubernetes-sigs/service-apis/pulls?q=is%3Apr+author%3Ahowardjohn+is%3Aclosed
- Issues responded to: 
- SIG projects I am involved with: service-apis and to some extent kind

**Comment by hbagdi** [comment]
+1

Thanks for your help in the project!

**Comment by robscott** [comment]
+1

Thanks for the help!

**Comment by bowei** [comment]
+1

**Comment by palnabarun** [comment]
Hi @howardjohn :wave:, thank you for applying to be a @kubernetes-sigs organization member.

Unfortunately, @hbagdi cannot sponsor you since @hbagdi is not an approver/reviewer in any of the OWNERS files ([Ref](https://go.k8s.io/owners/hbagdi)) and both @bowei and @robscott belong to the same company.

A requirement for sponsors is that they need to be from different companies. Can you please add one more sponsor satisfying all the guidelines mentioned in https://github.com/kubernetes/community/blob/master/community-membership.md#requirements?

Thank you. :slightly_smiling_face:

**Comment by savitharaghunathan** [comment]
Hi @howardjohn 👋 , please feel free to re-open this issue when you have one more sponsor satisfying all the guidelines mentioned in https://github.com/kubernetes/community/blob/master/community-membership.md#requirements. Thanks!

/close
