### ISSUE TITLE
REQUEST: New membership for reylejano

### ISSUE THREAD

**Issue by reylejano** [kubernetes/org#2348]
### GitHub Username
@reylejano

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @annajung 
- @jeremyrickard 
- @kikisdeliveryservice 

### List of contributions to the Kubernetes project
https://github.com/kubernetes/website/pull/25236
https://github.com/kubernetes/website/pull/24891
https://github.com/kubernetes/website/pull/23306

**Comment by annajung** [comment]
+1 

@reylejano has been part of sig release for multiple releases and currently is a doc shadow for 1.20 release.

**Comment by nikhita** [comment]
@reylejano looks like you were already part of the @kubernetes org but the bot removed you because of the change in username (`s/reylejano-rxm/reylejano`). The bot can't auto-update membership if username changes.

To get re-added to the org, you don't need new sponsors. :)

I have created https://github.com/kubernetes/org/pull/2349 to get you re-added to the org. Let me know if you need any more help on this! :smile:

**Comment by justaugustus** [comment]
Thanks Nikhita! Beat me to it :)

**Comment by reylejano** [comment]
@nikhita and @justaugustus Thank you!

**Comment by justaugustus** [comment]
Welcome back! :)
