### ISSUE TITLE
REQUEST: New membership for chrigl

### ISSUE THREAD

**Issue by chrigl** [kubernetes/org#251]
### GitHub Username
@chrigl

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @chaosaffe 
- @flaper87 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/94
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/100
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/89
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/95

- Issues responded to
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/106
https://github.com/kubernetes/kubernetes/issues/38498

- SIG projects I am involved with
  - sig-cluster-lifecycle
    - cluster-api
    - cluster-api-provider-openstack

/area github-membership

**Comment by chaosaffe** [comment]
I can only +1 for @kubernetes-sigs
@dims can you give Chris a +1 for @kubernetes?

**Comment by dims** [comment]
+1 from me!

**Comment by flaper87** [comment]
+1 from me!

**Comment by mrbobbytables** [comment]
@chrigl. Unfortunately, @flaper87 cannot sponsor you for membership in the @kubernetes org, but CAN sponsor you for the @kubernetes-sigs org. 

An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-incubator etc); as long as its a project they're involved with. 

However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-sigs cannot sponsor someone for membership in @kubernetes. They are scoped just to the org they're associated with.

If you'd like to amend your request to just @kubernetes-sigs, we can proceed with getting your membership processed. Otherwise, if you could, please find another sponsor from the @kubernetes org. 

If you have any questions don't be afraid to ask.

Thanks!

**Comment by chaosaffe** [comment]
@mrbobbytables Does https://github.com/kubernetes/cloud-provider-openstack/blob/master/OWNERS not count for @flaper87 being considered as an approver/reviewer within @kubernetes, or do you have to be an approver/reviewer within k/k?

**Comment by mrbobbytables** [comment]
@chrigl My apologies about the confusion regarding @flaper87's sponsorship. I've created PR #253 to add you to both the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification for both orgs :) 

Welcome to @kubernetes :tada:

/assign

**Comment by chrigl** [comment]
Thanks everyone :)
