### ISSUE TITLE
create driver-cluster-registrar

### ISSUE THREAD

**Issue by lpabon** [kubernetes/org#254]
### New Repo, Staging Repo, or migrate existing
kubernestes-csi/driver-cluster-registrar (filled in from kubernetes-csi/driver-registrar)

### Requested name for new repository
driver-cluster-registrar

### Which Organization should it reside
kubernetes-csi

### If not a staging repo, who should have admin access
saad-ali, lpabon

### If not a staging repo, who should have write access
saad-ali, lpabon

### If a new repo, who should be listed as approvers in OWNERS
saad-ali, lpabon

### If a new repo, who should be listed in SECURITY_CONTACTS
saad-ali, lpabon

### What should the repo description be
Sidecar container that registers the CSI driver with the Kubernetes cluster

### What SIG and subproject does this fall under in sigs.yaml
sig-storage

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

https://docs.google.com/document/d/1_hvq3nleqQEYatH9V_Gfep39jMzaFJRSN2ioA0PFq-Q/edit#heading=h.l7r2dou210l9

/area github-repo

**Comment by saad-ali** [comment]
@lpabon: I recommend the name `cluster-driver-registrar` instead of `driver-cluster-registrar`.
Also, merging this issue with https://github.com/kubernetes/org/issues/255 so we can track the work in one place.

----

kubernetes/org maintainers:

**Background:**

We are splitting https://github.com/kubernetes-csi/driver-registrar in to two new repos.

**Request**

Create two new repos named:
* https://github.com/kubernetes-csi/cluster-driver-registrar
* https://github.com/kubernetes-csi/node-driver-registrar


I approve this request from SIG-Storage.

**Comment by saad-ali** [comment]
@cblecker opened https://github.com/kubernetes/community/pull/2973

**Comment by cblecker** [comment]
Thanks @saad-ali! Let me know if you need anything else :)
/close
