### ISSUE TITLE
Remove OpenLab Github app for kubernetes-sigs/cluster-api-provider-openstack

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/org#2580]
### Organization or repository
kubernetes-sigs/cluster-api-provider-openstack

### Name of integration
OpenLab Zuul (not sure what the exact name is)

### Link to integration website
https://github.com/apps/theopenlab-ci

### Describe what is attempting to be accomplished
We want to remove the integration because we're not using it anymore (we migrated to Prow instead for our conformance tests)

### Additional context for request
* corresponding intall issue: https://github.com/kubernetes/org/issues/1400
* [cluster-api-provider-openstack: Remove OpenLab integration #785](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/785)

P.S.Probably the wrong repo for this request, but: (If there's another place to ask please send me there :))
* is there a way to delete accidentally pushed branches from the repo? 
* is there a way to make it possible to only push certain branches (with the rights (maintainer?) I currently have?)
* The branches I would like to cleanup are all those with prefix `to-be-deletd-`: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/branches/all

**Comment by nikhita** [comment]
@sbueringer :wave: We generally defer to the repo admins for these actions.

> We want to remove the integration because we're not using it anymore

Anyone from https://github.com/orgs/kubernetes-sigs/teams/cluster-api-provider-openstack-admins can remove the integration. If the admins list is stale, I'd recommend updating it by creating a PR against https://github.com/kubernetes/org/blob/d0ad9bcf60b8ca03806a8226a64f1eb42ad7b16d/config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml#L210

> is there a way to delete accidentally pushed branches from the repo?

Yes, admins would need to delete the branch protection for the branch-to-be-deleted from https://github.com/kubernetes-sigs/cluster-api-provider-openstack/settings/branches. After that's done, they can delete the branch from https://github.com/kubernetes-sigs/cluster-api-provider-openstack/branches.


> is there a way to make it possible to only push certain branches (with the rights (maintainer?) I currently have?)

There is no way to restrict which branches can be pushed if you have write access but fwiw I set `git remote set-url --push upstream no_push` to never push anything directly to the upstream repo.

> https://github.com/kubernetes-sigs/cluster-api-provider-openstack/branches/all

https://github.com/orgs/kubernetes-sigs/teams/cluster-api-provider-openstack-admins should be able to do this too. :+1: 


Since repo admins can take action here, I'm going to close this issue but please feel free to reopen if you'd like the org admins to step in and help!

**Comment by nikhita** [comment]
...Actually, spoke too soon :stuck_out_tongue: 

From the org admin side, we might need to clean up the integration entirely from the org. Removing the integration from the repo can be done by repo admins though. :+1: 

Reopening :)

**Comment by sbueringer** [comment]
@nikhita Thank you very much. `git remote set-url --push upstream no_push` should be enough for my use case. 

Did I get it right that we have to first remove it from the repo and then one of the org admins would remove it from the organization?

Although I'm not sure if we want to remove it from the whole org, I don't know if anybody except us (`cluster-api-provider-openstack`) is using it in the `kubernetes-sigs` org.

**Comment by nikhita** [comment]
> Did I get it right that we have to first remove it from the repo and then one of the org admins would remove it from the organization?

Yes, that's correct. 

> Although I'm not sure if we want to remove it from the whole org, I don't know if anybody except us (cluster-api-provider-openstack) is using it in the kubernetes-sigs org.

I checked the org-level configuration, it's only cluster-api-provider-openstack that uses it, so we should be good there. :+1:

**Comment by sbueringer** [comment]
@nikhita I'm now a repo admin, but I don't see the uninstall button:
![image](https://user-images.githubusercontent.com/4662360/112361793-0df44600-8cd4-11eb-969e-d3e1a205cadc.png)

Could it be that repo admins are not allowed to remove integrations? (I see a lot of other stuff which suggest I am in fact admin now)

**Comment by nikhita** [comment]
> Could it be that repo admins are not allowed to remove integrations? (I see a lot of other stuff which suggest I am in fact admin now)

Yes, it looks like only org admins can do that. I'll check with other org admins once before uninstalling the integration entirely. Will report back once it's done. :+1:

**Comment by nikhita** [comment]
The OpenLab GitHub app has been uninstalled. For the record:


`cluster-api-provider-openstack` was the only repo that used this app:

![Screenshot from 2021-03-25 16-30-03](https://user-images.githubusercontent.com/16105680/112462936-aa2b5500-8d87-11eb-8dfe-56e2f41f2872.png)


First, I tried removing the repo only but it didn't allow me to do that:

![Screenshot from 2021-03-25 16-30-16](https://user-images.githubusercontent.com/16105680/112463012-c0391580-8d87-11eb-9595-8249fa6e198c.png)


Then I uninstalled the app completely:

![Screenshot from 2021-03-25 16-30-28](https://user-images.githubusercontent.com/16105680/112463123-de9f1100-8d87-11eb-854f-ecc44aa92655.png)


Verified that this integration does not show up in the repo settings:

![Screenshot from 2021-03-25 16-34-31](https://user-images.githubusercontent.com/16105680/112463215-fd9da300-8d87-11eb-8bc8-5ea86f4fb889.png)

**Comment by sbueringer** [comment]
Thank you
