### ISSUE TITLE
Kubernetes-sigs org in artifacthub.io

### ISSUE THREAD

**Issue by marquiz** [kubernetes/org#2587]
### Organization or repository
kubernetes-sigs

### Name of integration
Artifact HUB (organization)

### Link to integration website
https://artifacthub.io/
https://artifacthub.io/packages/search?page=1&org=kubernetes-sigs (what we'd like to have)

### Describe what is attempting to be accomplished
I'd like to request that a **kubernetes-sigs** organization would be created in artifacthub.io. An org that would be managed by the Kubernetes project. My particular interest is related to the [Node Feature Discovery](https://github.com/kubernetes-sigs/node-feature-discovery) project that just started hosting a Helm chart repo and we'd like to add that to artifacthub.io, under the official kubernetes-sigs org.

### Additional context for request
Without better knowledge I'm submitting the issue here (also instructed in this direction on the #github-managemet slack channel)

**Comment by scottrigby** [comment]
Hi @marquiz 👋  we have a `kubernetes-sigs` Artifact Hub org set up. Once there are repos added to it, they will appear in the search.

This issue is perfect for transparency. I see you in the Node Feature Discovery [OWNERS](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/OWNERS) file 👍  Can you please note your artifact hub username here? Happy to add you. From that point on you will be able to create repos and also add others to that org as needed.

A few quick notes on adding other members to this org:
- Currently `kubernetes-sigs` is a flat Artifact Hub org, with only a few members so far. As it grows, it may be good to configure Artifact Hub [fine grained authorization](https://artifacthub.io/docs/topics/authorization/) (OPA policies may be added at any time), but we can cross that bridge any time it feels useful
- Until then, before adding other members, existing members should take the same precautions above (open an issue for transparency, check requesting GitHub user is listed in an OWNERS file of a repo under github.com/kubernetes-sigs)

**Comment by marquiz** [comment]
> we have a `kubernetes-sigs` Artifact Hub org set up. Once there are repos added to it, they will appear in the search.

Cool, I wasn't aware of that



> Can you please note your artifact hub username here?

Same as my Github username i.e. **marquiz**

**Comment by cpanato** [comment]
Can I help somehow?

**Comment by marquiz** [comment]
ping @scottrigby

**Comment by scottrigby** [comment]
@marquiz thanks for the woof/ping, you've been invited 👍
