### ISSUE TITLE
Request for new repo: kubernetes-sigs/windows-tools-dev-env

### ISSUE THREAD

**Issue by sladyn98** [kubernetes/org#2721]
### New Repo, Staging Repo, or migrate existing

Migrate repo from https://github.com/FriedrichWilken/KubernetesOnWindows to a new dev tools repo

### Requested name for new repository
sig-windows-dev-tools

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@jayunit100 @sladyn98 @FriedrichWilken @kubernetes/sig-windows-leads 

### If not a staging repo, who should have write access
@sladyn98 @FriedrichWilken @kubernetes/sig-windows-leads 

### If not a staging repo, who should be listed as approvers in OWNERS
@jayunit100 @perithompson @phillipsj @kubernetes/sig-windows-leads 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
e.g. alice, bob

### What should the repo description be
by default we will set it to "created due to (link to this issue)"

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for sig-windows

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
@jsturtevant @marosset @claudiubelu Just tagging the sig-windows leads on this for across the board approval

**Comment by jayunit100** [comment]
lets call it `sig-windows-dev-tools` @sladyn98 !

**Comment by jayunit100** [comment]
@nikhita can you help get this approved ?  @kubernetes/sig-windows-leads are all on board !

**Comment by jsturtevant** [comment]
This will be very helpful for new Windows contributors. Thanks @sladyn98 and @FriedrichWilken for starting this!

My only request is to add all the sig-windows leads to the admin/write/owners files. In the past we've needed access to repos for various maintenance reasons and didn't have it which required additional hoops to jump through before resolving issues.

**Comment by jayunit100** [comment]
SGTM!!!

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/sig-windows-dev-tools

Also created:
- https://github.com/kubernetes/org/pull/2757 - to add the GitHub team to grant access
- https://github.com/kubernetes/community/pull/5811 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

----

@FriedrichWilken and @phillipsj are not @kubernetes or @kubernetes-sigs org members and would need to [apply](https://github.com/kubernetes/community/blob/master/community-membership.md#member) for membership to get admin/approver access.

**Comment by cblecker** [comment]
As this is actually a transfer of an existing repo, I have deleted `kubernetes-sigs/sig-windows-dev-tools`, and we'll have to go through the additional steps for a transfer of an existing repository

**Comment by nikhita** [comment]
For the record, this [slack thread](https://kubernetes.slack.com/archives/C01672LSZL0/p1622737532031500) has more context.

**Comment by nikhita** [comment]
This is a transfer of an existing repo - https://github.com/FriedrichWilken/KubernetesOnWindows.

Following prerequisites need to be completed before we can migrate the repo.

- @sladyn98 can you please update the issue body to use the repo migration issue template?
- Add template files in https://github.com/kubernetes/kubernetes-template-project to the existing repo. Ensure that the README is also update to include the community and code of conduct sections.
- The existing LICENSE file is named incorrectly. s/LICENSE.md/LICENSE.
- Copyright headers are added to all files. This MUST only be done by @FriedrichWilken since they are an owner of the repo. See [rules](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#faq) for more details.
- @FriedrichWilken needs to sign the CNCF CLA.
- @FriedrichWilken and @phillipsj are not @kubernetes or @kubernetes-sigs org members and would need to [apply](https://github.com/kubernetes/community/blob/master/community-membership.md#member) for membership to get admin/approver access.

**Comment by sladyn98** [comment]
Update the issue to state its a repo migration.

**Comment by jayunit100** [comment]
friedrich is now in 
@sladyn98 .... can we proceed here?

**Comment by sladyn98** [comment]
@nikhita I guess we have followed all steps, can we move this on  ?

**Comment by nikhita** [comment]
We are close, a few more things!

- @luthermonson is a recent new contributor to the repo. They have not signed the [CLA](https://github.com/kubernetes/community/blob/master/CLA.md). They will need to sign the CLA before we can migrate the repo. Alternatively, you can revert their [commit](https://github.com/FriedrichWilken/KubernetesOnWindows/commit/5a182466357d8a0f7e44b9cfb0f4eef392471173) and add it back after they have signed the CLA.
- [OWNERS](https://github.com/FriedrichWilken/KubernetesOnWindows/blob/master/OWNERS#L5) and [SECURITY_CONTACTS](https://github.com/FriedrichWilken/KubernetesOnWindows/blob/master/SECURITY_CONTACTS#L13) should contain GitHub usernames instead of full names.

Once the above two points have been resolved, please ping me again on slack and I can migrate the repo! :)

**Comment by FriedrichWilken** [comment]
@nikhita 
[x] changed [OWNERS](https://github.com/FriedrichWilken/KubernetesOnWindows/blob/master/OWNERS#L5) to github usernames
[x] changed [SECURITY_CONTACTS](https://github.com/FriedrichWilken/KubernetesOnWindows/blob/master/SECURITY_CONTACTS#L13) to github usernames
[x] @luthermonson signed the CLA

:)

**Comment by nikhita** [comment]
Repo has been migrated - https://github.com/kubernetes-sigs/sig-windows-dev-tools :tada: 

Thanks for your patience with the process! We can close this issue once https://github.com/kubernetes/community/pull/5811 merges.

The GitHub team [sig-windows-dev-tools](https://github.com/kubernetes/org/blob/f433eb4b74edeca8b0cc6783225d8c7fcd8652dd/config/kubernetes-sigs/sig-windows/teams.yaml#L38) has admin access to the repo. @FriedrichWilken can you create a PR to add yourself to this team now that you are a member of the kubernetes-sigs GitHub org? :)
