### ISSUE TITLE
REQUEST: Create kube-scheduler-simulator

### ISSUE THREAD

**Issue by adtac** [kubernetes/org#2878]
### New repo, staging repo, or migrate existing

new repo

### Is it a staging repo?

no

### Requested name for new repository

kube-scheduler-simulator

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

adtac, alculquicondor, Huang-Wei

### Who should have write access?

sanposhiho

### Who should be listed as approvers in OWNERS?

adtac, alculquicondor, Huang-Wei

### Who should be listed in SECURITY_CONTACTS?

sanposhiho, adtac

### What should the repo description be?

A web-based simulator for the Kubernetes scheduler

### What SIG and subproject does this fall under?

sig-scheduling

### Please provide references to appropriate approval for this new repo

See comment from @Huang-Wei (sig-scheduling co-chair): https://github.com/kubernetes/kubernetes/issues/99605#issuecomment-893769322

### Additional context for request

This repository will host the code for a web-based kube-scheduler simulator. This is a GSoC project by @sanposhiho. I'd happy to explain more about the project if anyone wants me to, but you can also read the above issue to get more context.

cc @sanposhiho @Huang-Wei @alculquicondor

**Comment by Huang-Wei** [comment]
I fully support creating this repo.

**Comment by alculquicondor** [comment]
+1

**Comment by sanposhiho** [comment]
+1, thanks @adtac :)

**Comment by spiffxp** [comment]
Created repo:
- https://github.com/kubernetes-sigs/kube-scheduler-simulator

Opened PRs:
- add as subproject to sigs.yaml: https://github.com/kubernetes/community/pull/5951
- add teams: https://github.com/kubernetes/org/pull/2898

@sanposhiho you're going to need to go through the new membership process before we can add you as an org member or team member, please see https://github.com/kubernetes/community/blob/master/github-management/new-membership-procedure.md

@alculquicondor @Huang-Wei @adtac Generally the way I have done this with new contributors is to ask them to take on a good first issue or two, or submit a few PRs to a repo you and someone from another employer can review, so that sponsorship criteria are easy to meet

**Comment by spiffxp** [comment]
/close
Should be good to go
