### ISSUE TITLE
Netlify site for AdminNetworkPolicy API

### ISSUE THREAD

**Issue by astoycos** [kubernetes/org#3643]
### Repository

kubernetes-sigs/network-policy-api

### Project domain

adminnetworkpolicy-api.sigs.k8s.io

### Additional context for request

Following what was [done for the gateway api](https://github.com/kubernetes/org/issues/2506) to ultimately deploy a website for the new adminNetworkPolicy API defined here -> https://github.com/kubernetes-sigs/network-policy-api/pull/33

**Comment by astoycos** [comment]
@mrbobbytables I'm hoping you can help us out here :)... The source for the website is still in a PR https://github.com/kubernetes-sigs/network-policy-api/pull/33 but should be ready to go 

Please let me know if I missed any steps here to get this deployed (I tried to follow what the Gateway API folks did) 

Thanks in Advance!!

**Comment by astoycos** [comment]
In the meantime I also plan to deploy this on GH pages :)

**Comment by mrbobbytables** [comment]
Sorry, between being OOTO and other responsibilities I didn't get to this earlier - netlify has been configured, the site name right now kubernetes-sigs-network-policy-api.netlify.app 

Looking at the netlify.toml file in the root of the repo, it should be updated to be .app instead of .com and site name change to be kubernetes-sigs-network-policy-api - its too long with admin in the name of it for netlify >_<
There are also some build errors from the initial deploy test:
https://app.netlify.com/sites/kubernetes-sigs-network-policy-api/deploys/63233e95521a3a5e969288cc

**Comment by astoycos** [comment]
No problem, I will update the name and investigate the build errors, thanks so much @mrbobbytables! :)

**Comment by astoycos** [comment]
I wonder do I also need to fix this https://github.com/kubernetes/k8s.io/pull/4151/files now or is that just a nice TODO?

**Comment by mrbobbytables** [comment]
That'll need to get updated too for the dns non netlify dns name to work >_<

**Comment by astoycos** [comment]
Site is currently ip at https://kubernetes-sigs-network-policy-api.netlify.app/ And I just pushed an update to the DNS records

**Comment by astoycos** [comment]
Should be GTG now @mrbobbytables Thanks for all the help folks!

**Comment by cblecker** [comment]
I'm doing the Netlify piece right now :)

**Comment by astoycos** [comment]
Awesome, thanks for the help @cblecker!

**Comment by mrbobbytables** [comment]
Thanks @cblecker! I was just about to login myself lol

**Comment by cblecker** [comment]
Looks like everything is hooked up: https://network-policy-api.sigs.k8s.io/

Please let us know if you have any issues

/close
