### ISSUE TITLE
REQUEST: Create kubernetes-sigs/artifacts.k8s.io

### ISSUE THREAD

**Issue by justinsb** [kubernetes/org#3809]
### New repo, staging repo, or migrate existing

New Repo

### Is it a staging repo?

no

### Requested name for new repository

artifacts.k8s.io

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

justinsb, bentheelder, dims, ameukam, spiffxp, thockin

### Who should have write access?

justinsb, bentheelder, dims, ameukam, spiffxp, thockin

### Who should be listed as approvers in OWNERS?

justinsb, bentheelder, dims, ameukam, spiffxp, thockin

### Who should be listed in SECURITY_CONTACTS?

justinsb, bentheelder, dims, ameukam

### What should the repo description be?

This project exists to explore the creation of a redirector for artifacts.k8s.io, similar to the redirector for registry.k8s.io.

This project is experimental and may change drastically or be cancelled with little or no public notice.

### What SIG and subproject does this fall under?

sig-k8s-infra

### Please provide references to appropriate approval for this new repo

https://github.com/kubernetes/k8s.io/issues/4401#issuecomment-1301610446

**Comment by dims** [comment]
+1 from me

**Comment by ameukam** [comment]
+1 as k8s-infra SIG chair. 
(I'm also Github Admin)

**Comment by ameukam** [comment]
I would also suggest to a different name for the repo. We may reuse the logic for things other than `artifacts.k8s.io`.

**Comment by upodroid** [comment]
+1, I'm not sold on the idea of using a redirector instead of a CDN of our choice

**Comment by hh** [comment]
Agree with @upodroid, this does feel best served from a CDN, but this repo can be used to coordinate that effort.

**Comment by BenTheElder** [comment]
A cheap redirect service makes it easy to switch CDNs in the future with minimal fuss, or even to point at multiple CDNs, as funding requires. As of yet we don't actually have access to any new CDN funding.

We already have an architecture that works well for this, whether that then redirects to cloud front or fastly is a quickly alterable implementation detail. We can start with a simple S3 bucket and go from there, but putting our domain on a service we control that then forwards at the HTTP layer gives us the most control.

It's the same idea as the registry service. Consider also we may also want to serve small but sensitive shasum files differently from less trusted mirrors, or in the future we may use github binary downloads instead of any of the CDN/blob storage options as Azure's way of contributing (kind actually already has a crappier version of this by way of a netlify redirect `https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64` => github).

The point being, all of those options are readily available if we control a redirect in front, and they can be done with minimal disruption (just deploy a new redirect app version, no need to juggle certs etc)

**Comment by thockin** [comment]
+1

**Comment by ameukam** [comment]
@justinsb I suggest we call it `porche`. :-)

**Comment by ameukam** [comment]
Repo created: https://github.com/kubernetes-sigs/porche

Teams added: https://github.com/kubernetes/org/pull/3819
Ownership defined: https://github.com/kubernetes/community/pull/6961

**Comment by ameukam** [comment]
I think we can consider this done. 

Please, reopen the issue if there is something else that need to be done.

/close
