### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/cluster-api-provider-ibmcloud

### ISSUE THREAD

**Issue by Amulyam24** [kubernetes/org#5136]
### Repository

kubernetes-sigs/cluster-api-provider-ibmcloud

### Project domain

cluster-api-ibmcloud.sigs.k8s.io

### Additional context for request

1. New release v0.8.0 is out for kubernetes-sigs/cluster-api-provider-ibmcloud
2. This request was handled in an [earlier issue](https://github.com/kubernetes/org/issues/4983) but the link http://release-0-8.cluster-api-ibmcloud.sigs.k8s.io/ is not working
3. Need help to update this to point to the branch `release-0.8`

**Comment by Prajyot-Parab** [comment]
Updated Context
1. New release v0.9.0 is out for kubernetes-sigs/cluster-api-provider-ibmcloud

To update book we need the following:
- New URL to be active - http://release-0-9.cluster-api-ibmcloud.sigs.k8s.io/
- Point default book page (https://main.cluster-api-ibmcloud.sigs.k8s.io/) to above URL

2. release-0.8 URL to be active http://release-0-8.cluster-api-ibmcloud.sigs.k8s.io/

@cblecker Can you please help us with this one.
FYI - (this is the setup that we had done to configure it), maybe we need to retrigger something from here -  
https://github.com/kubernetes/org/issues/4318#issuecomment-1690322665

**Comment by mkumatag** [comment]
Instead of reaching out to others, could we request that contributors directly add to the Netlify project for our work? This way, we can avoid needing to involve the admins further :)

site link - https://app.netlify.com/sites/kubernetes-sigs-cluster-api-ibmcloud/deploys

@mrbobbytables I see you have helped others to add to the netlifty site as a team member, wondering if you can help us as well.

**Comment by Prajyot-Parab** [comment]
Resolved.
/close
