### ISSUE TITLE
migrate github.com/GoogleCloudPlatform/k8s-container-image-promoter

### ISSUE THREAD

**Issue by listx** [kubernetes/org#551]
### New Repo, Staging Repo, or migrate existing
Migrate https://github.com/GoogleCloudPlatform/k8s-container-image-promoter

### Requested name for new repository
container-image-promoter

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
listx, dims, hh, tpepper

### If not a staging repo, who should have write access
listx, dims, hh, tpepper

### If a new repo, who should be listed as approvers in OWNERS
listx, dims, hh, tpepper

### If a new repo, who should be listed in SECURITY_CONTACTS
listx, dims, hh, tpepper

### What should the repo description be
A tool to promote Docker images from one registry to another.

### What SIG and subproject does this fall under in sigs.yaml
This is part of the Release Engineering subproject for sig-release.

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)
See Jan 15, 2019 meeting minutes https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit
(Video link: https://youtu.be/Al1ClqqXyHk?t=2665)

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
Basically this tool lives in https://github.com/GoogleCloudPlatform/k8s-container-image-promoter but it should really live inside either kubernetes or the kubernetes-sigs org.

The promoter is an implemtation component for this KEP:  https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/k8s-image-promoter.md
Issue: https://github.com/kubernetes/k8s.io/issues/157

**Comment by spiffxp** [comment]
@listx I think in order to pull off the transfer, you'll need to add one of us to that repo with admin privileges

Looking to make sure the repo satisfies https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories..
> All contributors must have signed the CNCF Individual CLA or CNCF Corporate CLA
- yes, all three contributors have contributed code to kubernetes repos so I can verify they've signed the CLA
> Licenses of dependencies are acceptable; project owners can ping @caniszczyk for review of third party deps
- AFAICT the only dep is `gopkg.in/yaml.v2` which is fine
> Boilerplate text across all files should attribute copyright as follows: "Copyright <Project Authors>" if no CLA was in place prior to donation
- So there _was_ a CLA in place prior to donation, but it's the Google CLA.  I'm hoping we can accept that because we transitioned the Kubernetes project from Google's CLA bot to CNCF's CLA bot?  Otherwise there are a few "Copyright Google LLC" boilerplates that should probably be changed

**Comment by listx** [comment]
@spiffxp I added you and Caleb as admins to the repo.

RE Copryright boilerplate stuff, maybe @jdumars can weigh in on this?

**Comment by listx** [comment]
Sorry to double-post but yes, `gopkg.in/yaml.v2` is the only dependency.

**Comment by spiffxp** [comment]
Went digging for where that CLA line came from: https://github.com/kubernetes/community/pull/2049

I don't appear to have access to the service desk ticket to see the original text: https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-36

This was fun to dig up because for a while before this repo existed, repo donations were handled by the steering committee

Looking for prior art I found another repos that had code contributed by more than the originating author prior to the CNCF CLA check being enabled.  That said, the repo in question _did_ have the CNCF CLA check enabled prior to donation.  And their boilerplate headers referenced "The Kubernetes Authors" (eg: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/6e933b44d41b447a189b9d477661272d9827819f/pkg/cloud/cloud.go#L2)

**Comment by spiffxp** [comment]
Asked [kuberentes-sig-release@](https://groups.google.com/forum/#!topic/kubernetes-sig-release/ieLRsMYrmq8) and [kubernetes-sig-architecture@](https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/TjHLgJcDF-I)

**Comment by listx** [comment]
I am contributing this repo now to Kubernetes under the CNCF CLA.

**Comment by spiffxp** [comment]
TODO:
- Once https://github.com/kubernetes/org/pull/562 is merged and has taken effect, give the appropriate teams the appropriate ACLs

**Comment by nikhita** [comment]
I have completed the TODO. `k8s-container-image-promoter-admins` have admin access and `k8s-container-image-promoter-maintainers` have write access.

Additionally, I have removed direct admin access for @listx @spiffxp and @calebamiles since we prefer to grant permissions via teams.
@listx you should still have admin access over the repo because you are in the `k8s-container-image-promoter-admins` team.

Closing as done.
/close
