### ISSUE TITLE
REQUEST: New membership for Sai-Adarsh

### ISSUE THREAD

**Issue by Sai-Adarsh** [kubernetes/org#588]
### GitHub Username
@sai-adarsh

### Organization you are requesting membership in
@kubernetes 
@kubernetes-client
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @micw523 
- @roycaihw 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/community/issues/3087#issuecomment-466701716
https://github.com/kubernetes-client/gen/issues/85#event-2182104968
https://github.com/kubernetes-client/python/pull/766
https://github.com/kubernetes/website/pull/12992
- Issues responded to
https://github.com/kubernetes/website/issues/12823
https://github.com/kubernetes/community/issues/3087
- SIG projects I am involved with
https://github.com/kubernetes-client/python/pull/766
https://github.com/kubernetes/website/pull/12992

**Comment by mrbobbytables** [comment]
@Sai-Adarsh unfortunately @micw523  cannot sponsor for org membership. A sponsor must be an approver or reviewer in an associated org per the [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements). Do you happen to know someone else who could sponsor you?

**Comment by Sai-Adarsh** [comment]
@nikhita

**Comment by roycaihw** [comment]
@Sai-Adarsh thanks for your interest in contributing to Kubernetes org :)

Please follow the [instruction](https://github.com/kubernetes/org/blob/master/.github/ISSUE_TEMPLATE/membership.md#requirements) to speak with sponsors and get agreement before opening the application

I saw you have one PR merged kubernetes-client/python#766, but I don't see PR opened for https://github.com/kubernetes/community/issues/3087#issuecomment-466701716 and https://github.com/kubernetes-client/gen/issues/85#event-2182104968. Could you link to PRs if you are working on those issues? Also it looks like kubernetes/website#12992 is lacking activity. Is it close to getting merged? (and it looks like a dup of https://github.com/kubernetes/website/pull/12840?)

I'd suggest making multiple contributions to Kubernetes and re-applying, so that we gain more confidence in meeting the requirement https://github.com/kubernetes/community/blob/master/community-membership.md#requirements.

/close
