### ISSUE TITLE
Descrepencies between OWNER_ALIASES of community and org repo.

### ISSUE THREAD

**Issue by imkin** [kubernetes/org#605]
There are a lot of differences between the OWNER_ALIASES file of [community/](https://github.com/kubernetes/community/blob/master/OWNERS_ALIASES) repo and the [org/](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES) repo

Not sure where the deviation is. But I think whenever there is a commit to either of them a job/tool should synchronize the files on either repos.

**Comment by nikhita** [comment]
/assign

> But I think whenever there is a commit to either of them a job/tool should synchronize the files on either repos.

I think this is somewhat tricky because a bot would need to create a PR...and I'm not sure we want to encourage that for OWNERS files because we have a _lot_ of them across the org. :)

The solution to fixing this long-term is probably https://github.com/kubernetes/test-infra/issues/10065.

For the short-term, I'll look into fixing this by checking both the files. Going forward, we should also make sure that there are no one-off changes to `OWNERS_ALIASES` -- all changes should be a dump/copy of the `OWNERS_ALIASES` file in k/community.

**Comment by imkin** [comment]
Then probably we could choose one file as a "master".
Have a presubmit job that fails when the master OWNERS_ALIASES is not same as this one.
