### ISSUE TITLE
New kubernetes/cri-api github repository for staging the CRI API

### ISSUE THREAD

**Issue by dims** [kubernetes/org#642]
### New Repo, Staging Repo, or migrate existing
We need a new kubernetes/cri-api (similar to kubernetes/csi-api or kubernetes/node-api)

### Requested name for new repository
cri-api

### Which Organization should it reside
kubernetes

### If not a staging repo, who should have admin access
it is a staging repo.

### If not a staging repo, who should have write access
it is a staging repo.

### If a new repo, who should be listed as approvers in OWNERS
@dchen1107 @derekwaynecarr @dims 

### If a new repo, who should be listed in SECURITY_CONTACTS
@dchen1107 @derekwaynecarr @dims 

### What should the repo description be
`Container Runtime Interface (CRI) – a plugin interface which enables kubelet to use a wide variety of container runtimes`

### What SIG and subproject does this fall under in sigs.yaml
sig-node

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

- Approval from SIG-node : https://groups.google.com/d/msg/kubernetes-sig-node/1YDal_Pwq6k/ie3jVtstAwAJ
- Part of larger work separating CRI/dockershim from k/k : https://groups.google.com/d/msg/kubernetes-sig-architecture/UjeVR1N3yTo/RH4g3MZIAgAJ

### Additional context for request
closely related to the KEP being filed for dockershim : https://github.com/kubernetes/enhancements/pull/866

**Comment by dims** [comment]
cc @dchen1107 @derekwaynecarr @mikebrow @resouer @ddebroy

**Comment by mikebrow** [comment]
> ### Requested name for new repository
> cri-api

nit.. suggest `cri` by itself, the `api` suffix should not be necessary

**Comment by dims** [comment]
@mikebrow please see the existing patterns :) https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io

**Comment by nikhita** [comment]
It's too early here so maybe I missed something :) but this'll also need approval from sig-arch since this is a core repo: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#core-repositories

**Comment by dims** [comment]
Ack, i sent an email to them asking for approval:
https://groups.google.com/d/msg/kubernetes-sig-architecture/xtt1CbeSZzQ/mYQesFQTBAAJ

**Comment by mattfarina** [comment]
/approve

Note, @dims and @derekwaynecarr who are listed on this request are SIG Arch co-chairs as listed in https://github.com/kubernetes/community/tree/master/sig-architecture#leadership

**Comment by mikebrow** [comment]
> @mikebrow please see the existing patterns :) https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io

Two thoughts... why repeat a pattern out of convention that has no useful function... container runtime interface - application programming interface is a long winded collection of TLAs that repeats the word interface. Coming from a TLA company working on OSS I get the appeal :-) But there is no need to say interface twice, since CR**I** is an AP**I**. Thus the pattern of naming the Interfaces as such is secure by just saying CR**I** I suppose the one benefit of naming it CRI-API is we could then subsequently..  oh wait no can't think of one :-)

**Comment by dims** [comment]
@mikebrow noted, we should rather spend time on figuring out what else we need to do (see example [1]) than bikeshed on the name. Having been through transitions of some software  between DataPower / WebSphere / PureApplication / BlueMix / Softlayer brands in a previous life, this stuff is hard and let's keep the existing patterns.

[1] https://github.com/google/cadvisor/issues/2204

**Comment by dims** [comment]
We have +1 from me, @derekwaynecarr and @mattfarina So let's please go ahead with this.

**Comment by nikhita** [comment]
Repo created https://github.com/kubernetes/cri-api :tada: 

- PR to setup branch protection: https://github.com/kubernetes/test-infra/pull/11941
- **publishing-bot**:
   - PR against the publishing bot repo: https://github.com/kubernetes/publishing-bot/pull/170
   - PR to update rules against k/k: TODO. Will do this once a PR to create add the new repo to staging has been created, since it's easier to vet the dependencies list then.

Note: The OWNERS and SECURITY_CONTACTS listed here will be directly published from staging in k/k. I have created https://github.com/kubernetes/org/pull/653 to not ask these values in the issue template for staging repos from now on.

**Comment by dims** [comment]
Thanks a ton @nikhita

**Comment by nikhita** [comment]
Only thing that's left now: https://github.com/kubernetes/community/pull/3518

**Comment by dims** [comment]
Thanks a ton @nikhita !

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/3518 merged \o/

/close
