### ISSUE TITLE
Administration acls on sig sponsored sub-project repos.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/org#7]
### Organization or repository
e.g. kubernetes-sigs/*

### Users effected
sig-leads

### Describe the issue
The sigs leads/chairs who are responsible for a given sub-project needs team policies that enable maintainer level acls on those repos and teams.  

For examples: 
In https://github.com/kubernetes-sigs/cluster-api-provider-aws I do not have permissions to manage the teams and permissions.

**Comment by spiffxp** [comment]
/sig contributor-experience
/area github-management
ref: https://github.com/kubernetes/community/issues/2323

**Comment by spiffxp** [comment]
For the example: today, creating a new repo is a manual process.  I try to be consistent, making sure [teams are setup according to our current guidance](https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#team-guidance) but I missed a step of adding the teams to the repo in this case.  They've been added, and you should bug @detiber who's the team maintainer (since he was the person who [asked for the repo when steering was in charge of this](https://groups.google.com/a/kubernetes.io/d/msg/steering/A8-_jz9Qd2Y/wnHKg2CWBgAJ))

**Comment by timothysc** [comment]
So the problem is as follows: 

Organizational structure is hierarchical and permissions and rights show flow from this hierarchy.  Gitlab has this feature (https://docs.gitlab.com/ee/user/group/subgroups/).  

We now have an implicit hierarchy that is replicated in several locations and the permissions do not chain down from there.  A concrete example is the following: 
 
- sig-cluster-lifecycle 
  - cluster-api 
     - provider-x 
     - provider-y 

Within each repository there is a duplication of OWNERS which can be out of date over time.  Administrative permissions (e.g. maintainers) should flow through this hierarchy and have a single canonical source of truth (e.g. sigs.yaml) 

Right now I can just deal with it, but we need to fix aliases in OWNERS across orgs, and across repos so permissions are consistent.

**Comment by spiffxp** [comment]
Agree this is the direction we want to head.  Our first step will be driving the github side of things from a file that lives here, via [peribolos](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos)

Integration with OWNERS files and sigs.yaml are next steps that I haven't invested a lot of time in articulating.  There are conflicting views between distributed OWNERS files as the source of truth vs a single location (like sigs.yaml.) I'd prefer to reconcile one from the other, instead of trying to do anything bidirectional.  We may also find using GitHub teams instead of OWNERS_ALIASES would be a useful compromise.

**Comment by nikhita** [comment]
Trying to understand the issue better...today, we ask for who needs to be provided admin and write access to the repo in the issue template and create teams + grant access as part of the repo creation. Does that solve this issue?

>  We may also find using GitHub teams instead of OWNERS_ALIASES would be a useful compromise.

If the issue has boiled down to using GitHub teams in OWNERS files, maybe this should be another issue in k/test-infra?

**Comment by nikhita** [comment]
Can we close this in favour of https://github.com/kubernetes/test-infra/issues/10065?

**Comment by cblecker** [comment]
Yup, closing in favour of that issue. Thanks @nikhita!
