### ISSUE TITLE
new repo: kubernetes-sigs/structured-merge-diff

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/org#70]
### New Repo, or migrate existing
new repository

### Requested name for new repository
structured-merge-diff

### Which Organization should it reside
kubernetes-sigs

### Who should be provided access to this repository
@lavalamp, @apelisse, @jennybuckley (write)

### Approvals

SIG leads are agreed, see discussion in https://github.com/kubernetes/community/pull/2577

**Comment by spiffxp** [comment]
Created 
- https://github.com/kubernetes-sigs/structured-merge-diff
- https://github.com/orgs/kubernetes-sigs/teams/structured-merge-diff-admins
- https://github.com/orgs/kubernetes-sigs/teams/structured-merge-diff-maintainers

@lavalamp @apelisse are team maintainers for both teams

@jennybuckley has been invited to structure-merge-diff-maintainers and to the kubernetes-sigs org since they're already a kubernetes member

**Comment by spiffxp** [comment]
/close
Please ping here if there are any issues

**Comment by lavalamp** [comment]
Thanks for the rapid response!!
