### ISSUE TITLE
Project board for sig-node

### ISSUE THREAD

**Issue by yastij** [kubernetes/org#823]
### Organization or repository

kubernetes/kubernetes

### Users affected

none

### Describe the issue

As per discussion we had yesterday in the sig-node meeting, we are trying the ease the PR review workflow, we would like to request a project board for this
ref :https://github.com/kubernetes/kubernetes/pull/77914#issuecomment-492599952

cc @dims @derekwaynecarr

**Comment by nikhita** [comment]
/assign

@yastij I just created https://github.com/kubernetes/org/pull/824 to add the issue template for project boards. Could you edit the PR body to fill in the details as mentioned in the PR? :grimacing: 

And since this is a SIG-wide project board, I'll create it once either @derekwaynecarr or @dchen1107 approve the request.

**Comment by derekwaynecarr** [comment]
before we create new things, maybe we can just chat in our sig-node call or in a doc/slack how we see this board being used?  It’s probably the right thing, I just want to understand the process a bit.

**Comment by nikhita** [comment]
Looks like org members can create project boards themselves: https://github.com/kubernetes/test-infra/pull/12657#issuecomment-492730415

After there is consensus, please feel free to create the project board yourself. I'll keep this issue open in case you want to point people here while discussing about setting up the project board for SIG Node.

**Comment by nikhita** [comment]
:wave: just wanted to check if this issue can be closed or do you still need this to be open?

**Comment by nikhita** [comment]
Closing this since this doesn't need action from github admins. Please feel free to create the project board when ready. :)

Here's some more info regarding setting up project boards in kubernetes - https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#project-board-guidance.
