### ISSUE TITLE
Migrate pmorie/go-open-service-broker-client to kubernetes-sigs/go-open-service-broker-client

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes/org#893]
### New Repo, Staging Repo, or migrate existing
migrate existing

### Requested name for new repository
go-open-service-broker-client

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
the kubernetes-sigs team `service-catalog-admins`

### If not a staging repo, who should have write access
the kubernetes-sigs team `service-catalog-maintainers`

### If not a staging repo, who should be listed as approvers in OWNERS
the kubernetes-sigs team `service-catalog-maintainers`

### If not a staging repo, who should be listed in SECURITY_CONTACTS
jberkhahn

### What should the repo description be
A golang client for service brokers implementing the Open Service Broker API 

### What SIG and subproject does this fall under in sigs.yaml
this is part of the main service catalog project for sig-service-catalog.
it is already in use in the main repo, we're just moving it over to be under control
of the sig

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)
this was discussed at the April 22 meeting of SIG Service Catalog: [link](https://docs.google.com/document/d/17xlpkoEbPR5M6P5VDzNx17q6-IPFxKyebEekCGYiIKM/edit?usp=sharing)
pmorie's approval was obtained privately by @jboyd01

### Additional context for request
@pmorie will need to involved in moving this

**Comment by nikhita** [comment]
The meetings notes say `Discuss moving OSB Client API from pmorie to OSB GitHub org or Kub-Sig`. 

>  pmorie's approval was obtained privately by @jboyd01

@pmorie can you explicitly lgtm here for the record? Thanks!

**Comment by nikhita** [comment]
Donated repos need to satisfy some [requirements](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories). As per these requirements, the following steps need to be done before the migration:

- All contributors need to have the CNCF CLA signed.
@mook-as: you do not have the CLA signed. Could you sign the CNCF CLA so that https://github.com/pmorie/go-open-service-broker-client can be migrated to the Kubernetes project? Instructions for signing the CLA can be found [here](https://github.com/kubernetes/community/blob/master/CLA.md). :)

- The repo needs the following template files - `CONTRIBUTING.md`, `OWNERS`, `SECURITY_CONTACTS` -  to be incorporated into the Kubernetes project.
  - The repo already has a `code-of-conduct.md` but it references the CNCF CoC instead of the Kubernetes CoC. Can you update the `code-of-conduct.md` file and also the line about CoC in the README?
  - The template files can be found here - https://github.com/kubernetes/kubernetes-template-project.

- Files in the repo need to have the Kubernetes boilerplate header. Can you also add the boilerplate header to all relevant files?
  - You can find the boilerplate header here for different file extensions here - https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate
  - If you want to setup a verify script, https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/111 is an example that does this.
  - To automatically update the header across all files, you can also use https://github.com/kubernetes/repo-infra/pull/82.

- I ran a [FOSSA license scan](https://app.fossa.com/projects/git%2Bgithub.com%2Fnikhita-bot%2Fgo-open-service-broker-client?utm_source=share_link) for the repo and it's green, so all is good there. :+1:

**Comment by mook-as** [comment]
Huh, I seem to have missed the mail for this one somehow. Luckily, I've got my CLA fixed over in #894, so there's no action for me to do here at this point. 🎉

**Comment by jberkhahn** [comment]
Any update on this?

**Comment by nikhita** [comment]
/assign @pmorie 
for final go ahead

For the record, got an lgtm for this on slack - https://kubernetes.slack.com/archives/C232SF3TK/p1563895810010100.

I can take care of the OWNERS files, etc post migration but the copyright boilerplate will need to be added pre-migration because of legal rules...

**Comment by jberkhahn** [comment]
any update on this? what else needs to be done?

**Comment by nikhita** [comment]
https://github.com/pmorie/go-open-service-broker-client/pull/139 fixes the boilerplate for all files

**Comment by nikhita** [comment]
Repo has been migrated: https://github.com/kubernetes-sigs/go-open-service-broker-client and relevant teams have been granted access.

I have created https://github.com/kubernetes/community/pull/4065 to add the repo to sigs.yaml. Once the PR merges, we can close this issue.

**Comment by jberkhahn** [comment]
BAM! Thanks!
