### ISSUE TITLE
Request Netlify site for kubernetes/cloud-provider-vsphere

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/org#901]
### Repository
kubernetes/cloud-provider-vsphere (https://github.com/kubernetes/cloud-provider-vsphere/)

vSphere provider user docs using gitbooks + netlify

### Project domain
vsphere.sigs.k8s.io (https://github.com/kubernetes/k8s.io/pull/277) 

NOTE: Must match domain request.
See subproject site request docs for more information:
http://git.k8s.io/community/github-management/subproject-site-requests.md#subproject-domain-request

### Additional context for request
Any additional information or links to discussions regarding the request.

**Comment by nikhita** [comment]
Afaik up until now, we've always added a dns record after verifying that the site works fine.

https://kubernetes-sigs-cloud-provider-vsphere.netlify.com/ has been setup, but due to the redirects mentioned in https://github.com/kubernetes/cloud-provider-vsphere/blob/master/netlify.toml it redirects to https://vsphere.sigs.k8s.io/, which doesn't work because the DNS config hasn't been updated yet. :chicken: and :egg: problem!

 Netlify also allows to setup the redirects while setting it up, and I think it'll probably be better to have that configuration as the source of truth for redirects (i'm still figuring things around netlify so lmk if this is incorrect :))

So I see the next steps as:

- Remove the redirects section from netlify.toml
- Verify that https://kubernetes-sigs-cloud-provider-vsphere.netlify.com/ works
- Update DNS config
- :tada: 

cc @mrbobbytables

**Comment by andrewsykim** [comment]
@nikhita is there a way to point it at a temporary fork/branch? Want to avoid switching the config file back and forth in `master` if possible

**Comment by nikhita** [comment]
> is there a way to point it at a temporary fork/branch? 

I'm not sure if it's possible to point to a fork, but it is possible to point to a branch in the upstream repo.

**Comment by andrewsykim** [comment]
@nikhita pushed `vsphere-docs` branch in the upstream repo which removes the netlify redirects

**Comment by nikhita** [comment]
https://kubernetes-sigs-cloud-provider-vsphere.netlify.com/ works now! :+1:

**Comment by nikhita** [comment]
Changed the branch to `master` in netlify. 

Closing, but if you find anything weird on the next push to master, please ping me on slack or open this issue.

/close
